# Generated by Django 5.0.6 on 2024-11-17 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_remove_userlocation_user_id_userlocation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_ScrapDetails',
            fields=[
                ('Scrap_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Scrap_Name', models.CharField(max_length=50)),
                ('Current_Price_Per_KG', models.CharField(default=False, max_length=50)),
                ('Scrap_Image', models.TextField()),
                ('Price_Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_scrapdetails',
            name='Scrap_Image_Base64',
        ),
        migrations.AddField(
            model_name='scrap_selection',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrap_selection',
            name='order_otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scrap_selection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_scrapdetails',
            name='Current_Price_Per_KG',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_scrapdetails',
            name='Scrap_Image',
            field=models.TextField(),
        ),
    ]
