# Generated by Django 5.0.6 on 2024-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0006_dealer_scrapdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_details',
            name='Dealer_ID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
